### Crear un nuevo personal 
POST http://localhost:3000/api/personnel/create
Content-Type: application/json

{
  "nombre": "Roberto",
  "apellidos": "De la Rosa",
  "np": "191102",
  "rango": 1,
  "base": "supernumerario",
  "guardia": 1
}

### Actualizar el estado de un personal
PATCH http://localhost:3000/api/personnel/state/45
Content-Type: application/json

{
  "estado": 2
}

### Eliminar un personal guardado
DELETE http://localhost:3000/api/personnel/delete/45

### Recuperar todo el personal guardado
GET http://localhost:3000/api/personnel

### Recuperar a todo el personal vinculados a un rango
GET http://localhost:3000/api/personnel/rank/1

### Recuperar a todo el personal vinculados a una guardia
GET http://localhost:3000/api/personnel/guard/1

### Actualizar un personal por rango
PATCH http://localhost:3000/api/personnel/rank/45
Content-Type: application/json

{
  "rango": 3
}

### Actualizar un personal por guardia
PATCH http://localhost:3000/api/personnel/guard/45
Content-Type: application/json

{
  "guardia": 2
}
