### Crear un nuevo personal 
POST http://localhost:3000/api/personnel/create
Content-Type: application/json

{
  "nombre": "Roberto",
  "apellidos": "De la Rosa",
  "np": "191102",
  "rango": 1,
  "base": "supernumerario",
  "guardia": 1
}

### Actualizar un personal
PATCH http://localhost:3000/api/personnel/update/45
Content-Type: application/json

{
  "estado": 1,
  "rango": 1,
  "guardia": 1

}

### Eliminar un personal guardado
DELETE http://localhost:3000/api/personnel/delete/45

### Recuperar todo el personal guardado
GET http://localhost:3000/api/personnel

### Recuperar a todo el personal vinculados a un rango
GET http://localhost:3000/api/personnel/rank/1

### Recuperar a todo el personal vinculados a una guardia
GET http://localhost:3000/api/personnel/guard/1
