### Crear un nuevo día 
POST http://localhost:1234/api/dias/crear
Content-Type: application/json

{
  "personal": "a843cbd8-ca67-11ef-a95a-24842a45da79",
  "dia": "2025-01-09"
}

### Eliminar un día guardado
DELETE http://localhost:1234/api/dias/eliminar/0785cc54-cbbc-11ef-8762-48b2a523c160

### Recuperar todos los dias guardados
GET http://localhost:1234/api/dias
