### Crear una nueva estación
POST http://localhost:1234/api/estaciones/crear
Content-Type: application/json

{
  "nombre": "Departamento De Bomberos Acapulco Farallon",
  "ubicacion": "Cañada de los Amates S/n, Fraccionamiento Farallon del Obispo, 39690 Acapulco de Juárez, Gro.",
  "estado": "02ee9c01-c8c0-11ef-a95a-24842a45da79"
}

### Eliminar una estación guardada
DELETE http://localhost:1234/api/estaciones/eliminar/986c34c0-c98c-11ef-a95a-24842a45da79

### Recuperar todas las estaciones guardadas
GET http://localhost:1234/api/estaciones

### Recuperar estacion por nombre
GET http://localhost:1234/api/estaciones/Cuartel de Bomberos Acapulco - Central Farallon
