### Recuperar todos los estados guardados
GET http://localhost:1234/api/estados

### Recuperar estado por id
GET http://localhost:1234/api/estados/id/d51598a6-c728-11ef-a95a-24842a45da79

### Recuperar estado por nombre
GET http://localhost:1234/api/estados/inactivo
