### Crear un nuevo rango
POST http://localhost:1234/api/rangos/crear
Content-Type: application/json

{
  "nombre": "militar"
}

### Eliminar un rango guardado
DELETE http://localhost:1234/api/rangos/eliminar/ea7c89ed-cd47-11ef-8762-48b2a523c160

### Recuperar todos los rangos guardados
GET http://localhost:1234/api/rangos
