### Crear un nuevo servicio
POST http://localhost:1234/api/servicios/crear
Content-Type: application/json

{
  "creado": "f55edd06-e830-11ef-85fb-a6ecab92db95",
  "nombre": "Alejandra Lopez", 
  "telefono": "9211734040", 
  "salida": "02:10", 
  "llegada": "02:20", 
  "control": "02:40", 
  "base": "02:55", 
  "incidente": "abejas", 
  "ubicacion": "Calle 15 entre calle 19 Col. Icacos",
  "otro": "", 
  "observaciones": "Se talo un arbol de roble que estaba recargado sobre una barda",
  "unidades": [
    "8fb79927-ee4a-11ef-ad0e-8b272236a8a6",
    "8fb79fd2-ee4a-11ef-ad0e-8b272236a8a6"
  ],
  "personal": [
    "bef6c5b7-e82b-11ef-8b35-3b80d3a0aa71",
    "bef78044-e82b-11ef-8b35-3b80d3a0aa71",
    "bef78604-e82b-11ef-8b35-3b80d3a0aa71",
    "bef78892-e82b-11ef-8b35-3b80d3a0aa71",
    "bef79c6a-e82b-11ef-8b35-3b80d3a0aa71"
  ],
  "incendio": {
    "inmueble": "",
    "inmEspecifique": "",
    "otro": "",
    "otrEspecifique": ""
  },
  "fuga": {
    "fuga": "",
    "especifique": "",
    "capacidad": "",
    "empresa": "",
    "material": "",
    "noGuia": "",
    "observaciones": ""
  },
  "abejas": {
    "abejas": "",
    "especifique": "",
    "observaciones": ""
  },
  "rescate": {
    "heridos": "",
    "cadaveres": "",
    "ambulancia": "",
    "equipo": "",
    "noPersonal": "",
    "especifique": ""
  },
  "daños": {
    "material": "",
    "especifique": "",
    "heridos": "",
    "muertos": "",
    "ambulancia": ""
  },
  "legales": {
    "legales": "",
    "otro": ""
  }
}

### Eliminar un servicio 
DELETE http://localhost:1234/api/servicios/eliminar/3e0eb0c1-826e-4d59-81be-b35ed62e81af

### Obtener todos los servicios
GET http://localhost:1234/api/servicios

### Obtener un servicio por el id
GET http://localhost:1234/api/servicios/7d7356c4-c351-4e07-a5c4-b1239d6970ac

### Obtener los servicios por el creador
GET http://localhost:1234/api/servicios/creado/4838bb62-0ef1-48f0-9b35-83a1d0a70b29