### Actualizar un usuario
PATCH http://localhost:1234/api/usuarios/actualizar/f3d94723-cd4d-11ef-8762-48b2a523c160
Content-Type: application/json

{
  "rol": "ac624e32-cd46-11ef-8762-48b2a523c160",
  "estado": "aeaa26d7-cd46-11ef-8762-48b2a523c160"
}

### Eliminar un usuario guardado
DELETE http://localhost:1234/api/usuarios/eliminar/938e60fb-c953-11ef-a95a-24842a45da79

### Recuperar todos los usuarios guardados
GET http://localhost:1234/api/usuarios