### Crear una nueva vación  
POST http://localhost:1234/api/vacaciones/crear
Content-Type: application/json

{
  "personal": "a843cbd8-ca67-11ef-a95a-24842a45da79",
  "inicio": "2025-01-10"
}

### Eliminar una vacación
DELETE http://localhost:1234/api/vacaciones/eliminar/c6c28742-cb2e-11ef-a95a-24842a45da79

### Recuperar todas las vacaciones
GET http://localhost:1234/api/vacaciones
