### Crear una nueva unidad
POST http://localhost:1234/api/types/create
Content-Type: application/json

{
  "nombre": "camion"
}

### Actualizar una unidad
PATCH http://localhost:1234/api/types/state/bd1aa3fb-fd2b-11ef-a43b-4955ce09c2b0
Content-Type: application/json

{
  "estado": "a52e31fe-faea-11ef-b9d1-a2cc1a1d4502"
}

### Eliminar la unidad guardada
DELETE http://localhost:1234/api/types/delete/9b82e6a4-faeb-11ef-b9d1-a2cc1a1d4502

### Recuperar todas las types guardadas
GET http://localhost:1234/api/types