### Crear una nueva unidad
POST http://localhost:3000/api/types/create
Content-Type: application/json

{
  "nombre": "motocicleta"
}

### Actualizar una unidad
PATCH http://localhost:3000/api/types/state/5
Content-Type: application/json

{
  "estado": 2
}

### Eliminar la unidad guardada
DELETE http://localhost:3000/api/types/delete/5

### Recuperar todas las types guardadas
GET http://localhost:3000/api/types