### Crear una nueva unidad
POST http://localhost:3000/api/units/create
Content-Type: application/json

{
  "tipo": 5, 
  "numero": "101"
}

### Actualizar una unidad
PATCH http://localhost:3000/api/units/state/19
Content-Type: application/json

{
  "estado": 2
}

### Eliminar la unidad guardada
DELETE http://localhost:3000/api/units/delete/19

### Recuperar todas las units guardadas
GET http://localhost:3000/api/units