### Actualizar estado del usuario
PATCH http://localhost:3000/api/users/state/1
Content-Type: application/json

{
  "estado": 1
}

### Actualizar rol del usurio 
PATCH http://localhost:3000/api/users/role/1
Content-Type: application/json

{
  "rol": 1
}

### Eliminar un usuario guardado
DELETE http://localhost:3000/api/users/delete/1

### Recuperar todos los usuarios guardados
GET http://localhost:3000/api/users

### Recuperar un usuario guardado por el id
GET http://localhost:3000/api/users/1