### Crear un nuevo rol 
POST http://localhost:3000/api/roles/create
Content-Type: application/json

{
  "nombre": "usuariosa",
  "descripcion": "Rol para usuarios normales con acceso limitado."
}

### Actualizar el estado de un rol
PATCH http://localhost:3000/api/roles/state/5
Content-Type: application/json

{
  "estado": 2
}

### Eliminar el rol guardado
DELETE http://localhost:3000/api/roles/delete/1

### Recuperar todos los roles guardados
GET http://localhost:3000/api/roles