### Crear un nuevo rango
POST http://localhost:3000/api/ranks/create
Content-Type: application/json

{
  "nombre": "militar"
}

### Actualizar un rango
PATCH http://localhost:3000/api/ranks/state/5
Content-Type: application/json

{
  "estado": 2
}

### Eliminar un rango guardado
DELETE http://localhost:3000/api/ranks/delete/5

### Recuperar todos los rangos guardados
GET http://localhost:3000/api/ranks
