### Crear una nueva guardia
POST http://localhost:1234/api/guards/create
Content-Type: application/json

{
  "guardia": "3er Guardia",
  "estacion": "ecbe3852-ca51-11ef-a95a-24842a45da79"
}

### Eliminar una guardia guardada
DELETE http://localhost:1234/api/guards/delete/38e27e60-ca5d-11ef-a95a-24842a45da79

### Recuperar todas las guardias guardadas
GET http://localhost:1234/api/guards

### Recuperar todas las guardias guardadas vinculadas a una estación
GET http://localhost:1234/api/guards/544891fd-faeb-11ef-b9d1-a2cc1a1d4502
